name: deploy vue
on:
    push:
        branches: [ main ]

jobs:
    deploy-app:
        runs-on: ubuntu-latest
        steps:
            -   name: check out the code to build server
                uses: actions/checkout@v4
            -   uses: pnpm/action-setup@v4
                with:
                    run_install: false
            -   name: Use Node.js 20.x
                uses: actions/setup-node@v4
                with: 
                    node-version: 20
                    cache: 'pnpm'
            -   name: build the code
                run: |
                    pnpm install --no-frozen-lockfile
                    pnpm build
            -   name: set the ubuntu user as the owner of the /var/www/html directory for ubuntu 24+
                uses: appleboy/ssh-action@v1.2.0
                with:
                    host: ${{secrets.PROD_HOST}}
                    username: ${{secrets.SSH_USER_NAME}}
                    key: ${{secrets.SSH_KEY}}
                    script: |
                        sudo chown -R ubuntu /var/www/html
            -   name: copy file to server
                uses: appleboy/scp-action@master
                with:
                    host: ${{secrets.PROD_HOST}}
                    username: ${{secrets.SSH_USER_NAME}}
                    key: ${{secrets.SSH_KEY}}
                    source: "./dist/*"
                    target: "/var/www/html"
                    strip_components: 1
            -   name: set the ubuntu user as the owner of the /var/www/html directory for ubuntu 24+
                uses: appleboy/ssh-action@v1.2.0
                with:
                    host: ${{secrets.PROD_HOST}}
                    username: ${{secrets.SSH_USER_NAME}}
                    key: ${{secrets.SSH_KEY}}
                    script: |
                        sudo chown -R ubuntu /var/www/html
